# Coding Standards

There is no naming convention that is "standard" in R and SQL but there are typically used practices. Coding practices are to help your future self and others understand and continue your work. 

**General**

  + Introduction header – State the purpose or goal of the code, your name, and any other information that can help anyone get up to speed on the code. Maintain a log of changes with a date to indicate what was last changed - this isn’t always necessary, but this is good for projects that will be continue to be reused.
  
  Below is a sample header you can use at the top of an R script.
  
```{r sample_header, eval=FALSE}
# header ----                                                                  #
#                                                                              #
# Filename: 01_describe_what_your_script_does.R                                #
# Path: data/01_describe_what_your_script_does.R                               #
# Author: Your Name                                                            #
# Date created: 2025-10-15                                                     #
# Date modified: 2025-10-31                                                    #
# Purpose: Describe why you would use this script.                             #
# Inputs: Identify any files, dependencies, etc. this script requires.         #
# Outputs: Identify any named outputs, files, etc. this script produces.       #
# Notes: Add any additional notes, links, etc. for others to execute your      #
#        code properly.                                                        #

```
  

  + Use informative names – In naming variables or functions it is always good to make informative names to help make sense of the code. Not too short and not too long, just enough to be concise and informative. 

## Language R
### Projects
There are three general approaches we use for our work for a R project, the more methodic approach is ProjectTemplate which can be found in the project section of this manual. A report style approach which is good for short and quick assignments. A shiny project which has UI controls and is used for scenarios where the information needs to be absorbed in multiple perspectives.   

  + ProjectTemplate
  + rmd
  + shiny

### Variables 
  + Use underscore_separated a.k.a. snake_case: e.g. my_data_set
  + Being descriptive and specific: e.g. raw_act_2022_2023

### Functions
  + The use case for a function is for reuseability. Don’t copy paste code, create a function.
  + When naming your function use lowerCamelCase: e.g., addTaskCallback <- function()
  + Start with a verb when naming your function. i.e., add, make, create, populate, do
  + Stay in scope
  + Avoid Global Variables at all costs - Think of a function as a receipt, the function should take in all the items you need to make your outcome.

### dplyr
Use dplyr from tidyverse as it is designed to enable dataframe manipulation in an intuitive, user-friendly way.



## Language SQL 

### Hard bracket encapsulation
  + SELECT [FirstName] FROM [Students] WHERE [AcademicYear] =  ‘2021-2022’

### Variables
  + Use Camel Case: DECLARE &#64;AcademicYear VARCHAR(9) 

### Joins
  + Know your joins and know your data.
