# Specific Projects

The R&A Team works on all sorts of projects and topics. This section provides more information about our specific projects.

Some of our data analysis and evaluation work is done on an annual basis, such as annual performance reporting (APR) on grant-funded evaluations and analyzing academic performance on state standardized tests or student persistence data. In some project areas, we analyze data and share updates on a weekly or monthly basis (i.e., senior college applications, ACT test scores). We also conduct in-depth analyses that may involve multiple methods including quantitative, machine learning, and qualitative methods to gain breadth and depth for understanding a particular topic. 

This chapter briefly describes where we [Store and Share][Store and Share], annual and related [Evaluation Projects][Evaluation Projects], and other specific projects such as [First Year Teacher Project][First Year Teacher Project] and [Math Curriculum Redesign][Math Curriculum Redesign].


## Store and Share

Where do we save our work on specific projects? Work is stored in different places depending on the project and team member(s). Generally, work is stored in Wrike for project management of ongoing projects and ad hoc requests, GitHub repositories for version control, and [R&A Private Group][R&A Private Group] folders for accessibility and collaboration. 

How do we share our work on specific projects? [Projects][Projects] describes outlets for publishing and sharing results, findings, reports, and dashboards. 

### R&A Private Group

The R&A Private Group documents folder provides a convenient and accessible storage place for all R&A team members to access shared folders and documents. Highly useful for projects that require multiple team members, storing and accessing files the private group folder helps to ensure consistency and continuity of work. 

The R&A Private Group documents folder is not to be confused with the [Team Site (TheHub)][Team Site (TheHub)] or the [Team Site (TheHub)][Team Site (TheHub)] documents folder. 


## Evaluation Projects

The R&A team evaluates four (4) annually funded grants including: 1) 21st Century Afterschool Program, 2) Camp Rio, 3) Charter School Program, and Teacher and School Leader Incentive Program. In addition to annual grant-funded evaluations, R&A conducts evaluation work for ad hoc evaluations and specific projects as needed and by request. 


### Evaluation Plans 

How do we organize and guide our work on evaluation projects? Evaluation plans are prepared for each annually funded grant and published to our Team Site. Annual evaluation projects may include several specific projects that directly inform the ongoing evaluation work. Evaluation plans are also developed for ad hoc and specific evaluation needs, topics, and projects.

Evaluation Plans are prepared annually to...be continued. The purpose of evaluation plans are to..be continued from policy and guidelines content files.

Evaluation Plans for the current fiscal year are published to the [Team Site (TheHub)][Team Site (TheHub)]. 

Evaluation planning resources and files are stored in the [R&A Private Group][R&A Private Group] Evaluation folder.


### Annual Evaluation Projects



#### 21st Century Afterschool Program

IDEA Public Schools’ 21st Century Afterschool program provides high quality programming for students in the hours before and after the traditional school day has ended. The afterschool program allows IDEA schools to make a positive difference in the lives of students with greatest needs, as the program aims to provide additional support and ensure that all students are receiving the guidance and assistance they need to successfully progress towards college completion. The 21st Century program is centered around four main goals for students: increasing achievement scores, improving student behavior and attendance, and increasing rates of graduation or grade promotion towards timely graduation. 

During the 2021-2022 school year, the majority of IDEA schools implementing the Afterschool Program were funded by the 10th cycle of the 21st Century grant or by the Elementary and Secondary School Emergency Relief Fund (ESSER). These schools were located in the South Texas and Rio Grande Valley and served students from pre-K through 12th grade. The following campuses were funded by the 21st Century grant: IDEA Alamo, IDEA Donna, IDEA Frontier, IDEA McAllen, IDEA Mission, IDEA Pharr, IDEA Quest, IDEA San Benito, IDEA San Juan, and IDEA Weslaco. The following campuses were covered by ESSER funds: IDEA Brownsville, IDEA Edinburg, IDEA Elsa, IDEA Harlingen, IDEA La Joya, IDEA Los Encinos, IDEA North Mission, IDEA Owassa, IDEA Palmview, IDEA Rio Grande City, IDEA Robindale, IDEA Riverview, IDEA Sports Park, IDEA Toros, IDEA Tres Lagos, IDEA Weslaco Pike. In addition, IDEA Health Professions was funded by the Department of Education and IDEA Innovation was funded by the Louisiana Department of Education.

The Afterschool Program evaluation plan for school year 2022-2023 can be found [here](https://ideapublicschoolsorg.sharepoint.com/:b:/s/ResearchandAnalysis/EezZf9Bi5y5MpSGLsz5mzGoBRKe6kiUfvGiHdBpGG7KQzg?e=xMZGZg). The 2021-2022 program evaluation annual report can be found [here](https://ideapublicschoolsorg.sharepoint.com/:b:/s/ResearchandAnalysis/EfjTPNC0hG5ChfbgFsVdILUBEIyWU2KQ252cdCSpb0qNIA?e=0QpEQO).

More information to come later.

Student participation in the Afterschool program is tracked in PowerSchool and then pulled into the R&A data warehouse server. The program coordinators track the programs that the students participate in and if they have participated for more that 45 days. Students that participate 45 days or more are classified as "Regular Participants". Student that participate for fewer than 45 days are classified as "Non-Regular Participants".

**Database:** [RGVPDRA-DASQL].[Program21stCentury].[dbo].[Students]

* **_[dbo].[Students]_**  This table tracks student program and activity participation. 

**Important columns:**

* **[FIRST_NAME]:** Student First Name
* **[LAST_NAME]:** Student Last Name
* **[STUDENT_NUMBER]:** Student local ID number (108 number)
* **[ACADEMIC_SUPPORT]:** Participation in academic support programs (0/1 indicator)
* **[COLLEGE_CAREER_READINESS]:** Participation in College and Career Readiness programs (0/1 indicator)
* **[FAMILY_ENGAGEMENT]:** Participation in Family Engagement programs (0/1 indicator)
* **[ENRICHMENT]:** Participation in Enrichment programs (0/1 indicator)
* **[WHENCREATED]:** Date when the record was created
* **[WHENMODIFIED]:** Date when the record was modified

A flag was added at the beginning of the 2022-2023 school year to indicate if the student participated 45 days or more.


From Chapter 4 (Temporary Insert):

The 21st Century Afterschool Programs provide students with afterschool opportunities to get academic support, college and career guidance, as well as family engagement activities. These programs are funded through several avenues, such as a grant from the Texas Education Agency, federal ESSER funds, the Department of Education, and the Louisiana Department of Education. The programs are offered at 26 campuses in the RGV, Health Professions in Austin, and Innovation in Louisiana. 

  + **FIRST_NAME:** the student's first name;
  + **LAST_NAME:** the student's last name;
  + **STUDENT_NUMBER:** the student's 108 number;
  + **ACADEMIC_SUPPORT:** binary indicator for participation in academic support activities;
  + **COLLEGE_CAREER_READINESS:** binary indicator for participation in college and career readiness activities;
  + **FAMILY_ENGAGEMENT:** binary indicator for participation in family engagement activities;
  + **WHENCREAATED:** a date/time stamp indicating the date of participation;
  + **WHENMODIFIED:** a date/time stamp indicating the date when the record was modified. Most values are null.

#### Camp Rio

More information to come soon.


#### Charter School Program (CSP) Grants

R&A conducts internal evaluation work for two CSP grants:
1) CSP Grants 2019-2024 and 2) CSP Grants 2020-2025. 

CSP Grant 2017-2022 evaluation work was conducted by a contracted agency.

Charter School Program (CSP) grants awarded to IDEA Public Schools provide funds for replication and expansion of new IDEA schools. Replication refers to launching new schools. Expansion refers to scaling new schools. 

CSP grant applications were submitted and approved for funding. The grant application provides general guidance for evaluation. CSP evaluation work is informed by evaluation questions and aims to address the following areas: implementation of the IDEA model, needs and challenges, supports, and sustainability strategies. Primary metrics for reporting outcomes include student enrollment, student persistence, student academic performance, and employee retention.

* **CSP Schools and Regions**
CSP evaluation focuses on schools launching or scaling during SY 2018-2019, 2019-2020, 2020-2021, 2021-2022, 2022-2023, 2023-2024, and 2024-2025 in 12 regions. 

* **Regions:** Rio Grande Valley, San Antonio, Austin, El Paso, Baton Rouge, Tarrant County, Permian Basin, Houston, Tampa, Jacksonville, Cincinnati, and Headquarters.

* **Schools:** List schools. 

Most schools open or launch with Kindergarten, 1st, and 2nd grades at the Academy level and 6th grade at the College Prep level. However there are exceptions to this model. 

* **School Opening Grade Exceptions:** 
* Price Hill opened with 6th and 7th at the CP level
* Converse opened with PK, K, and 1st at the Academy level
* Hidden Meadow opened with PK, K, and 1st at the Academy level

* **Changes to School Numbers & Names**
Below is a tables documenting the changes to School Numbers:

| School Name | School Short Name | School Number | Academic Year |
| :------- | :------- | -------: | :-------: |
| IDEA Hope Academy | Hope | 12001 | 2021-2022 |
| IDEA Hope Middle School | Hope | 12002 | 2021-2022 |
| IDEA Hope College Prep | Hope | 12003 | 2021-2022 |
| IDEA Victory Academy | Victory | 12004 | 2021-2022 |
| IDEA Victory Middle School | Victory | 12005 | 2021-2022 |
| IDEA Victory College Prep | Victory | 12006 | 2021-2022 |
| IDEA Hope Academy | Hope | 78400 | 2022-2023 |
| IDEA Hope Middle School | Hope | 78401 | 2022-2023 |
| IDEA Hope College Prep | Hope | 78402 | 2022-2023 |
| IDEA Victory Academy | Victory | 78350 | 2022-2023 |
| IDEA Victory Middle School | Victory | 78351 | 2022-2023 |
| IDEA Victory College Prep | Victory | 78352 | 2022-2023 |


And this table has changes to school Names (specifically, Amber Creek to Robinson)

| School Name | School Number | State School Number | Academic Year |
| :------- | -------: | -------: | :-------: |
| IDEA Amber Creek Academy | 108807304 | 108807304 | 2021-2022 |
| IDEA Amber Creek Middle School | 109907026 | 108807204 | 2021-2022 |
| IDEA Amber Creek College Prep | 108807204 | 108807204 | 2021-2022 |
| IDEA Robinson Academy | 108807304 | 108807304 | 2022-2023 |
| IDEA Robinson Middle School | 109907026 | 108807204 | 2022-2023 |
| IDEA Robinson College Prep | 108807204 | 108807204 | 2022-2023 |


* **CSP Evaluation Questions:** insert question here. 

* **CSP Evaluation Question 1:** insert question here. 


To address the first question, the IDEA model and its components needed to be identified. 

* **CSP IDEA Model:**

More information to come soon. 




#### Teacher and School Leader Incentive Program (TSLIP)

Grant that contains 4 key components/areas for research questions. Main points of analysis: Level 5 Pilot Program and "Best Practices" library; TCP Level percentages by District/Region/Campus/School and look at percentage and distribution of TCP Level 5 teachers across schools and possibly down to grade level.


More information to come soon.


### Ad Hoc Evaluation Projects


## Other Specific Projects

### Teacher Hiring and TCP Project

Teacher Hiring is a project for the HA team to help inform selection processes for hiring teachers. This is an on-going project that started in Spring 20-21 with Anitra and has transferred over to Martin Winchester and Emily Neilson. There have been multiple rounds of correlations and modeling examining the relationship between 5 pre-determined pre-hire selection measures and teacher performance, as indicated and measured by TCP (level and composite score). The first round looked at regressions models with each separate pre-hire selection measure predicting TCP level/composite score, and then a model using all 5 pre-hire selection measures to predict TCP level/composite score. Next, a selection score was created by allotting points to the different selection measures, in accordance with the HA Team's guidelines on how various selection measures are scored. The models were rerun. In all cases, very little to no correlation or predictive power was found in these relationships. 

The scope of this project in initial rounds was limited to only those who were hired, or in the Jobvite data column "Hire Y/N", Hire=Yes. Predictions of TCP scores could not be made for those applicants who were not hired.

Later and current rounds have focused on ML techniques to do the modeling instead of limiting it to only linear regression and correlation matrices. Missingness of the data was a key issue in this decision. Over 50% of the data was not present in Jobvite, as candidates were not required to fill in all the sections nor all the pre-hire selection measures. These were left as optional. One recommendation of the R&A team was to require all sections to be completed by applicants on the Jobvite application and prior to hire, and then to collect and record this data. Another recommendation was to collect and record Writing Task Scores. 99% of those scores were not recorded, but this Writing Task was 12 points of the First Hurdle selection score in the selection process. For the Machine Learning applications, we have included all the missing data and coded it with it's own value, and then it was run through the ML algorithms. We were looking to see if "not filling in" certain information or all one's pre-hire selection measure data on the application had a relationship to poorer outcomes on TCP.

Data was provided originally by Brittany Vasquez from the HA team, and from Alfredo from Tyler Munis.

#### Jobvite Data

Obtained from HA team. It is the data from the candidates who apply for IDEA jobs through Jobvite. Not all candidates applied through Jobvite in the past, but HA is trying to streamline the application process and require all applicants for all jobs (at all campuses) to apply through a central system, which is Jobvite. 

A particular Jobvite file is labeled with a year, such as "Jobvite 19-20", and it will have column "Candidate Submit Date", which is a range from October 2019 to July 2019 (October to July, proceeding the year the applicant will likely begin work). An applicant from that range will most likely have a Start Date of August 2019 (or sometime in the calendar year 2019, starting AFTER the 19-20 Academic Year). However, there are cases when applicants will, for example, apply during the 10/2018 - 07/2019 cycle (Jobvite 19-20), but will not have a Start Date until 2020 or 2021 (so they do not start the following Fall after the application cycle). 
          
This data has columns including Candidate Full Name, Candidate Email (personal email used for the application), and some of the pre-hire selection measures, such as GPA. However, all 5 of the pre-hire selection measures are not included yet (Stem Major, Teach For America status, Experience prior to IDEA, GPA, and Teacher Certification). The data also has no Employee IDs yet, as this is a list of candidates. There is a Hire Yes/No column, which has "Yes" for those candidates who were offered a position and "No" for those who were not offered a position. Also, there is a Requisition ID which is basically an application ID number, and it is unique per application. If a single candidate applies for more than one position, the candidate will have a unique ID for each application.

#### Teacher Export Data

This is found on the TCP application, a website: [tcp.ideapublicschools.org]. To gain access, contact Nohemi Pizana and request access. Use your IDEA login credentials to access the site. Teacher Export reports have the composite score, placement level, subject, job title, employee ID, and a few pre-selection hiring measures.


#### TCP Handbook

This is the link to the TCP Handbook, which denotes the business rules to advance thought the different TCP Levels, 1 through 5. https://ideapublicschools.org/wp-content/uploads/2021/08/TCP-Revised-Rubrics-2020-2021.Sept_.25.2020.pdf


#### Teacher Interviews/Teacher Manager Interviews

A job analysis is being conducted to try to find job-relatedness for functions conducted in the teacher role, as well as to help identify pre-hire selection measures for the HA team to help with the selection process. This involves a series of neutrally-phrased questions to illicit responses about the teacher role, what a teacher does, what makes a successful IDEA teacher, what characteristics a teacher needs to succeed at IDEA. Both teachers and teacher-managers (principals, PIRs, and APIs) are being interviewed to collect this qualitative data set. These should be completed by Fall 2022 SY.


### First Year Teacher Project

This was a project for HA. Malinda Hardy and Martin Winchester headed it as our partners in HA. IT was started in Fall 21, for the 21-22 SY. The research question examined was "How do first-year teachers do compared to teachers with other tenure on student achievement?" To examine this question, we obtained the Semester Exam data for 20-21 SY and ran our models. The 21-22 SY data was not out at the time, so we set up the coding and models so that later we could just plug in the 21-22 SY data when it was available. We plugged in this data  in Spring 22, when it was available in late January/early February. Visuals including box plots were created to show the median pass rate per teacher. First, boxes were broken into two categories: 1st year teacher and non-first-year teacher. There was little difference in the median pass rates (pass rates meant the student had achieved Approaches, Meets, or Masters on the semester exam, taken at the end of the 21-22 SY Fall Semester). Next, 6 groups were created and compared: 1st year, 2nd year, 3rd year, 4th year, and 5th+ year (anyone was 5 years or more in tenure at IDEA). There was also little difference in the median pass rates, for both 20-21 SY and 21-22 SY. One reason could be because everyone, regardless of tenure at IDEA was a "first year teacher online" for remote teaching, during the pandemic. 

#### 3 Years of Data Used in Analysis

In subsequent rounds, the 19-20 SY data was looked at for semester exams and compared to 20-21 SY and 21-22 SY. Since students took their 19-20 SY semester exams in the Fall semester of that academic year, they took them before the pandemic and the lock-down (which happened in Spring 2020). Hence, this is "pre-pandemic" data. This data did show slight differences in the median pass rates between first year and other years of teaching, namely, 3rd, 4th, and 5th years of teaching.

The analysis further looked at individual subjects (ELA, Math, Science, History-Social Studies, Foreign Language, and Technology). Those six subjects were chosen because they all take semester exams. There were individual differences depending on which subject was examined. The analysis also looked at College Prep vs. Academy, and looked at the results by Region (showing the results for each campus within the respective region).

Results were presented to Malinda Hardy via PowerPoint by Maura and for some rounds, Steven. There were 4 rounds and each round was added to the same PowerPoint presentation. 

#### Project Transfered to Ann Heller

This project has been transferred over to Ann Heller because Melinda is leaving and Ann is taking over the New Teacher Institute. This transfer happened in late May/Early June 2022, and Ann has no research questions for us at this time after giving her a short PowerPoint presentation overview of the prior 4 rounds. She may come back in the Fall/October 2022 with more questions.


### Math Curriculum Redesign Project

This project was examining the differences between student achievement for pilot vs. non-pilot schools, for a new math curriculum that is being implemented. The pilot was not set up at-random, and project design was not created by R&A. It was challenging to find meaningful results because it was hard to tease apart the impacts of particular things on student achievement. It was difficult to know if a change in test scores was due to the new curriculum or something else. The results showed that although the test scores may not have been significantly different/better for pilot than the non-pilot schools, the pilot schools lowest scores were not as low as the non-pilot schools. In effect, the pilot schools did not do worse in terms of the lowest scores, so we could likely say the the new math curriculum was not harming the students (although it was hard to say if it was helping). We may revisit this project for AP classes and help our partners design the pilots and project design for the next round, which will hopefully support getting more meaningful results from the analysis.


### Team Value Proposition Project

August to October 2022, R&A conducted multiple methods of analyses on data collected by the HA team to provide greater understanding about the depth and breadth of employees' attitudes, beliefs, experiences, and perceptions about working at IDEA. 

