# Evaluation Projects

The R&A team evaluates four (4) annually funded grants including: 1) 21st Century Afterschool Program, 2) Camp Rio, 3) Charter School Program, and Teacher and School Leader Incentive Program. In addition to annual grant-funded evaluations, R&A conducts evaluation work for ad hoc evaluations and specific projects as needed and by request. 


### Evaluation Plans 

How do we organize and guide our work on evaluation projects? Evaluation plans are prepared for each annually funded grant and published to our Team Site. Annual evaluation projects may include several specific projects that directly inform the ongoing evaluation work. Evaluation plans are also developed for ad hoc and specific evaluation needs, topics, and projects.

Evaluation Plans are prepared annually to...be continued. The purpose of evaluation plans are to..be continued from policy and guidelines content files.

Evaluation Plans for the current fiscal year are published to the [Team Site (TheHub)][Team Site (TheHub)]. 

Evaluation planning resources and files are stored in the [R&A Private Group][R&A Private Group] Evaluation folder.


### Annual Evaluation Projects



#### 21st Century Afterschool Program

IDEA Public Schools’ 21st Century Afterschool program provides high quality programming for students in the hours before and after the traditional school day has ended. The afterschool program allows IDEA schools to make a positive difference in the lives of students with greatest needs, as the program aims to provide additional support and ensure that all students are receiving the guidance and assistance they need to successfully progress towards college completion. The 21st Century program is centered around four main goals for students: increasing achievement scores, improving student behavior and attendance, and increasing rates of graduation or grade promotion towards timely graduation. 

During the 2021-2022 school year, the majority of IDEA schools implementing the Afterschool Program were funded by the 10th cycle of the 21st Century grant or by the Elementary and Secondary School Emergency Relief Fund (ESSER). These schools were located in the South Texas and Rio Grande Valley and served students from pre-K through 12th grade. The following campuses were funded by the 21st Century grant: IDEA Alamo, IDEA Donna, IDEA Frontier, IDEA McAllen, IDEA Mission, IDEA Pharr, IDEA Quest, IDEA San Benito, IDEA San Juan, and IDEA Weslaco. The following campuses were covered by ESSER funds: IDEA Brownsville, IDEA Edinburg, IDEA Elsa, IDEA Harlingen, IDEA La Joya, IDEA Los Encinos, IDEA North Mission, IDEA Owassa, IDEA Palmview, IDEA Rio Grande City, IDEA Robindale, IDEA Riverview, IDEA Sports Park, IDEA Toros, IDEA Tres Lagos, IDEA Weslaco Pike. In addition, IDEA Health Professions was funded by the Department of Education and IDEA Innovation was funded by the Louisiana Department of Education.

The Afterschool Program evaluation plan for school year 2022-2023 can be found [here](https://ideapublicschoolsorg.sharepoint.com/:b:/s/ResearchandAnalysis/EezZf9Bi5y5MpSGLsz5mzGoBRKe6kiUfvGiHdBpGG7KQzg?e=xMZGZg). The 2021-2022 program evaluation annual report can be found [here](https://ideapublicschoolsorg.sharepoint.com/:b:/s/ResearchandAnalysis/EfjTPNC0hG5ChfbgFsVdILUBEIyWU2KQ252cdCSpb0qNIA?e=0QpEQO).


Student participation in the Afterschool program is tracked in PowerSchool and then pulled into the R&A data warehouse server. The program coordinators track the programs that the students participate in and if they have participated for more that 45 days. Students that participate 45 days or more are classified as "Regular Participants". Student that participate for fewer than 45 days are classified as "Non-Regular Participants".

**Database:** [RGVPDRA-DASQL].[Program21stCentury].[dbo].[Students]

* **_[dbo].[Students]_**  This table tracks student program and activity participation. 

**Important columns:**

* **[FIRST_NAME]:** Student First Name
* **[LAST_NAME]:** Student Last Name
* **[STUDENT_NUMBER]:** Student local ID number (108 number)
* **[ACADEMIC_SUPPORT]:** Participation in academic support programs (0/1 indicator)
* **[COLLEGE_CAREER_READINESS]:** Participation in College and Career Readiness programs (0/1 indicator)
* **[FAMILY_ENGAGEMENT]:** Participation in Family Engagement programs (0/1 indicator)
* **[ENRICHMENT]:** Participation in Enrichment programs (0/1 indicator)
* **[WHENCREATED]:** Date when the record was created
* **[WHENMODIFIED]:** Date when the record was modified

A flag was added at the beginning of the 2022-2023 school year to indicate if the student participated 45 days or more.


From Chapter 4 (Temporary Insert):

The 21st Century Afterschool Programs provide students with afterschool opportunities to get academic support, college and career guidance, as well as family engagement activities. These programs are funded through several avenues, such as a grant from the Texas Education Agency, federal ESSER funds, the Department of Education, and the Louisiana Department of Education. The programs are offered at 26 campuses in the RGV, Health Professions in Austin, and Innovation in Louisiana. 

  + **FIRST_NAME:** the student's first name;
  + **LAST_NAME:** the student's last name;
  + **STUDENT_NUMBER:** the student's 108 number;
  + **ACADEMIC_SUPPORT:** binary indicator for participation in academic support activities;
  + **COLLEGE_CAREER_READINESS:** binary indicator for participation in college and career readiness activities;
  + **FAMILY_ENGAGEMENT:** binary indicator for participation in family engagement activities;
  + **WHENCREAATED:** a date/time stamp indicating the date of participation;
  + **WHENMODIFIED:** a date/time stamp indicating the date when the record was modified. Most values are null.

#### Camp Rio

Camp RIO has been in operation since 2015 as a year-round outdoor education and summer camp facility. It is located on 85-acres of predominantly untouched wildlife preserve in Brownsville, Texas and is accessible to all regardless of school district, ability, or age. Camp RIO is a facility designed for outdoor discovery and adventure with a mission of promoting healthy lifestyles by exposing children to the benefits of exploration, land stewardship, and staying active through various hands-on activities. 

The program provides guided outdoor activities such as fishing, canoeing, building campfires, geocaching, hiking, and archery which help connect participants to their community and nature. From its inception in 2015, the number of students attending Camp Rio per year has increased from a few hundred to over 28,000 students in the 2021-2022 school year.

The program evaluation for Camp Rio focuses on 3 main goals:
  1) To understand the short- and long-term association between students’ participation in Camp RIO and students’ interests in natural resources and land stewardship 
  2) To evaluate the short- and long-term association between participation in Camp RIO and student academic achievement and well-being  
  3) To understand the long-term association between participation in Camp RIO and student college and career choices in the natural sciences  
 The evaluation plan for school year 2022-2023 can be found [here]( FINAL_FY 22-23_CampRio_Plan.pdf). The 2021-2022 annual report can be found [here]( CR_Annual_Report_2021-2022_DRAFT_8.09.22.pdf).



#### Charter School Program (CSP) Grants

R&A conducts internal evaluation work for two CSP grants:
1) CSP Grants 2019-2024 and 2) CSP Grants 2020-2025. 

CSP Grant 2017-2022 evaluation work was conducted by a contracted agency.

Charter School Program (CSP) grants awarded to IDEA Public Schools provide funds for replication and expansion of new IDEA schools. Replication refers to launching new schools. Expansion refers to scaling new schools. 

CSP grant applications were submitted and approved for funding. The grant application provides general guidance for evaluation. CSP evaluation work is informed by evaluation questions and aims to address the following areas: implementation of the IDEA model, needs and challenges, supports, and sustainability strategies. Primary metrics for reporting outcomes include student enrollment, student persistence, student academic performance, and employee retention.

* **CSP Schools and Regions**
CSP evaluation focuses on schools launching or scaling during SY 2018-2019, 2019-2020, 2020-2021, 2021-2022, 2022-2023, 2023-2024, and 2024-2025 in 12 regions. 

* **Regions:** Rio Grande Valley, San Antonio, Austin, El Paso, Baton Rouge, Tarrant County, Permian Basin, Houston, Tampa, Jacksonville, Cincinnati, and Headquarters.

* **Schools:** List schools. 

Most schools open or launch with Kindergarten, 1st, and 2nd grades at the Academy level and 6th grade at the College Prep level. However there are exceptions to this model. 

* **School Opening Grade Exceptions:** 
* Price Hill opened with 6th and 7th at the CP level
* Converse opened with PK, K, and 1st at the Academy level
* Hidden Meadow opened with PK, K, and 1st at the Academy level

* **Changes to School Numbers & Names**
Below is a tables documenting the changes to School Numbers:

| School Name | School Short Name | School Number | Academic Year |
| :------- | :------- | -------: | :-------: |
| IDEA Hope Academy | Hope | 12001 | 2021-2022 |
| IDEA Hope Middle School | Hope | 12002 | 2021-2022 |
| IDEA Hope College Prep | Hope | 12003 | 2021-2022 |
| IDEA Victory Academy | Victory | 12004 | 2021-2022 |
| IDEA Victory Middle School | Victory | 12005 | 2021-2022 |
| IDEA Victory College Prep | Victory | 12006 | 2021-2022 |
| IDEA Hope Academy | Hope | 78400 | 2022-2023 |
| IDEA Hope Middle School | Hope | 78401 | 2022-2023 |
| IDEA Hope College Prep | Hope | 78402 | 2022-2023 |
| IDEA Victory Academy | Victory | 78350 | 2022-2023 |
| IDEA Victory Middle School | Victory | 78351 | 2022-2023 |
| IDEA Victory College Prep | Victory | 78352 | 2022-2023 |


And this table has changes to school Names (specifically, Amber Creek to Robinson)

| School Name | School Number | State School Number | Academic Year |
| :------- | -------: | -------: | :-------: |
| IDEA Amber Creek Academy | 108807304 | 108807304 | 2021-2022 |
| IDEA Amber Creek Middle School | 109907026 | 108807204 | 2021-2022 |
| IDEA Amber Creek College Prep | 108807204 | 108807204 | 2021-2022 |
| IDEA Robinson Academy | 108807304 | 108807304 | 2022-2023 |
| IDEA Robinson Middle School | 109907026 | 108807204 | 2022-2023 |
| IDEA Robinson College Prep | 108807204 | 108807204 | 2022-2023 |


* **CSP Evaluation Questions:** insert question here. 

* **CSP Evaluation Question 1:** insert question here. 


To address the first question, the IDEA model and its components needed to be identified. 

* **CSP IDEA Model:**

More information to come soon. 




#### Teacher and School Leader Incentive Program (TSLIP)

Grant that contains 4 key components/areas for research questions. Main points of analysis: Level 5 Pilot Program and "Best Practices" library; TCP Level percentages by District/Region/Campus/School and look at percentage and distribution of TCP Level 5 teachers across schools and possibly down to grade level.


More information to come soon.


### Ad Hoc Evaluation Projects
