# Platforms

This section of the R&A Manual concerns details on the various software platforms we use: General purpose of the software, some details on how to use for your project, and useful links.

## Qualtrics

Qualtrics is a survey and data collection platform. It allows for survey building, distribution of links via email or text, response analysis and reporting. A particularly useful feature of Qualtrics is the ability to upload a list of emails address with information associated with each email address and then send a personalized survey link to each email address selected from the list. For example, in surveying district teachers one may want their responses disaggregated by race/ethnicity, school of employment, and grade level. This information can be linked to each teacher’s email address and uploaded into Qualtrics prior to surveying the teachers. As data is collected, each response will have the uploaded pieces of information associated to it.

The following sessions outline how to create a survey, upload and list of email addresses to surveyed, and create a basic live report for your survey. 

### Creating a Survey

More to come

### Creating and Uploading a Participant List

More to come

### Exporting Survey Response Data

More to come
