--- 
title: "IDEA R&A Manual"
author: "Chris Haid, Edison Coronado, Rodrigo San Miguel, Mishan Jensen, Maura Carter, Steven Macapagal"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is IDEA Public Schools' Research & Analysis Team's ever evolving encyclopedia of resources and best practices."
---

# A little about this manual {#about}

The *IDEA R&A Manual*  is [IDEA Public Schools'](www.ideapublicschools.org) Research & Analysis Team's ever evolving encyclopedia of resources and best practices.  It's purpose is to make any R&A team member's (or really any other interested reader's) job easier, by sharing how we do our jobs.   

The manual is particularly aimed at a technical audience (e.g. statisticians, data analysts, data engineers, data scientists) and most contributions are from technical authors. Indeed, the expectation is that technical members for the R&A team will contribute to this manual regularly (i.e., weekly or daily during the festive (information) harvesting celebration of Doctoberfest)


```{r include=FALSE}
library(tidyverse)


# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```


## What goes in this manual?

Anything and everything we learn during the course of our work at IDEA. Of particular help is any information, learning, or insights, but some topics that are especially useful to your colleages (and our future self) include:

* Locations of important tables in [the data warehouse][The Data Warehouse]
* Information about how to use data in the warehouse (e.g. how do you [identify students in CSI](#csi)
* Links and examples to useful R packages
* [Tips and tricks] in R, SQL, or Python that you discover in the course of your work 
* Templates:  output templates, input templates, [ProjectTemplates](#section-ProjectTemplate), . . . all the templates. 

## How do you contribute to this book?

This manual is written in **Markdown** and managed with git/Github. 

::: {.tip}
If you are unfamiliar with git/Github you'll want to read through[ how we use git in the Projects chapter](#section-github)
:::

The general process is as follows:

1. Clone the repo:  If you haven't already, pull this book down [from it's Github repo](https://github.com/idea-analytics/r_and_a_manual).  From the command line run `git clone https://github.com/idea-analytics/r_and_a_manual.git`.
1.  Or, pull down the latest version of the master branch `git checkout master` and then `git pull`
1.  In File Explorer/Finder find the `r_and_a_manaul` folder and double click `r_and_a_manual.Rproj`, which will open the book's project in RStudio
1. Check out a branch `git checkout -b my-manual-update`.
1.  Make updates.  You can run in R `bookdown::serve_book` to have it recompile the book on save. 
1. Commit frequently.
1. Push your changes on yoru branch up to Github.
1.  Intitiate a pull request to merge your changes.  If they are minor you can do the whole process your self. IF they are major--especially changing the books structure--then have another team member review your pull request before merging. 
1. Complete the merge. 
1. Rinse and repeat!

::: {.tip}
Remember each Rmd file contains one and only one chapter, and a chapter is defined by the first-level heading `#`.  Use second (`##`) and third (`###`) level headings for sections in each chapter. 
:::
